name: test
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  grammar-test:
    name: Grammar Test
    strategy:
      matrix:
        os: [macos-12, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    container:
      image: kusionstack/kclvm-builder
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Grammar test
        run: make test-grammar
        shell: bash

  konfig-test:
    name: Konfig Test
    runs-on: ubuntu-latest
    container:
      image: kusionstack/kclvm-builder
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Konfig test
        run: | 
          make test-konfig
        shell: bash

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    container:
      image: kusionstack/kclvm-builder
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: unit test
        run: | 
          make test-unit
        shell: bash
